# Generated by Django 5.2.7 on 2025-10-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
