# Generated by Django 5.2.7 on 2025-10-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_quotation_company_quotation_landing_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='grade_spec',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='lead_time_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
